name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
    - name: Executar testes
      run: |
        python -m unittest discover
